rule all:
    input: ["foo.txt", "bar.txt"]

rule timeout:
    resources:
        runtime = lambda wildcards, attempt: 2**(attempt - 1) * 1
    output: "foo.txt"
    threads: lambda wildcards, attempt: 2**(attempt -1) * 1
    shell:
        "echo Threads: {threads} > {output};"
        "sleep 80"

rule bar:
    resources:
        runtime = 1
    output: "bar.txt"
    shell:
        "echo bar > {output}"


rule excessive_runtime:
    resources:
        runtime = 10000
    output: "runtime.txt"
    shell:
        "echo {resources} > {output}"


rule excessive_memory:
    resources:
        mem_mb = 2000
    output: "memory.txt"
    shell:
        "echo {resources} > {output}"


rule memory_with_constraint:
    resources:
        mem_mb = 800
    output: "memory_with_constraint.txt"
    shell:
        "echo {resources} > {output}"
        
rule short_queue:
    output: "short_queue.txt"
    shell: "touch {output}"