rule all:
    input: ["foo.txt", "bar.txt"]

rule timeout:
    resources:
        runtime = lambda wildcards, attempt: 2**(attempt - 1) * 1
    output: "foo.txt"
    threads: 2
    shell:
        "echo foo > {output};"
        "sleep 80"

rule bar:
    resources:
        runtime = 1
    output: "bar.txt"
    shell:
        "echo bar > {output}"
